# Change these first
owner: Overlord-Factions # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: "Server"
    check: "tcp-ping"
    url: overlordmc.net
    port: 25565
  - name: "Server Website"
    url: https://overlordmc.net
  - name: "Server Map"
    url: https://map.overlordmc.net
  - name: "Server Stats (Admin Only)"
    url: https://stats.overlordmc.net
  - name: "Management Panel (Admin Only)"
    url: https://panel.overlordmc.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: dark
  cname: uptime.overlordmc.net
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/YeYHwjF.png
  name: OVERLORD Uptime
  introTitle: "Welcome to **OVERLORDMC** status page!"
  introMessage: This site shows current status of all services ran by OVERLORDMC, if status here is positive and you still have trouble, let us know on [discord](https://discord.gg/cR6WACk3cp).
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://overlordmc.net
    - title: Discord
      href: https://discord.gg/cR6WACk3cp

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
